#!/usr/bin/env bash
#
# Bootstrap a new system
# Set sym links
#
# Used https://github.com/holman/dotfiles/blob/master/script/bootstrap as
# the base

# DOTFILES_ROOT="`pwd`"
DOTFILES_ROOT="$HOME/dotfiles"

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

setup_directories () {
  mkdir -p $HOME/.vim/colors
}

## Make directories
info "Making directories"
setup_directories

## Clone dotfiles
info "Cloning dot files"
git clone --recursive https://github.com/ebruning/dotfiles.git

## Symlink files
## Personal files
link_files $DOTFILES_ROOT/vimrc $HOME/.vimrc
link_files $DOTFILES_ROOT/gitconfig $HOME/.gitconfig
link_files $DOTFILES_ROOT/gitignore_global $HOME/.gitignore_global
link_files $DOTFILES_ROOT/zshrc $HOME/.zshrc

## Custom zsh theme
# link_files $DOTFILES_ROOT/agnoster.zsh-theme $DOTFILES_ROOT/oh-my-zsh/custom/agnoster.zsh-theme

## System settings
info "Writing system settings"
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseHorizontalScroll -bool NO
defaults write com.apple.finder QLEnableTextSelection -bool TRUE
defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1
defaults write com.apple.dashboard mcx-disabled -boolean YES

## Install brew and brew bundle
## TODO: handle having to sudo before installing brew
cd $DOTFILES_ROOT
info "Installing homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

info "Installing brew bundle"
brew tap Homebrew/bundle

info "Installing bundle applications"
brew bundle

## Install vim plugin manager
info "Installing vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

##Install ruby
info "Installing Ruby 2.2.1"
rbenv install 2.2.1
rbenv global 2.2.1
