#!/usr/bin/env bash
#
# Bootstrap a new system
# Set sym links
#
# Used https://github.com/holman/dotfiles/blob/master/script/bootstrap as
# the base

DOTFILES_ROOT="`pwd`"

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

setup_directories () {
  mkdir -p $HOME/.uncrustify
}

## Clone oh-my-zsh
git clone git://github.com/robbyrussell/oh-my-zsh.git DOTFILES_ROOT/oh-my-zsh

## Clone my atom config files
git clone https://github.com/ebruning/atom.git DOTFILES_ROOT/atom

## Synlink files
link_files DOTFILES_ROOT/vimrc $HOME/.vimrc
link_files DOTFILES_ROOT/gitconfig $HOME/.gitconfig
link_files DOTFILES_ROOT/zshrc $HOME/.zshrc
link_files DOTFILES_ROOT/atom $HOME/.atom
link_files DOTFILES_ROOT/kolo.zsh-theme $HOME/oh-my-zsh/custom/kolo.zsh-theme
link_files DOTFILES_ROOT/uncrustifyconfig $HOME/.uncrustify/uncrustify.cfg

## System settings
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseHorizontalScroll -bool NO
defaults write com.apple.finder QLEnableTextSelection -bool TRUE
defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1
defaults write com.apple.dashboard mcx-disabled -boolean YES 
